{
    'name': 'my app',
    'version': '12.0.1.0',
    'summary': 'my app',
    'author': "www.mypscloud.com",
    'website': 'https://www.mypscloud.com/',
    'category': 'Tools',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/home_views.xml',
        'views/lesson_views.xml',
        'views/subject_views.xml',
    ],
    'demo': [],
    'qweb': [],
    'js': [],
    'css': [],
    'auto_install': False,
    'application': True,
}
